foreground   #bbabd2
background   #040309
cursor       #bbabd2

color0       #040309
color8       #827793
color1       #372A94
color9       #372A94
color2       #5A37B2
color10      #5A37B2
color3       #7452A3
color11      #7452A3
color4       #5838CF
color12      #5838CF
color5       #B46D9F
color13      #B46D9F
color6       #8658AA
color14      #8658AA
color7       #bbabd2
color15      #bbabd2
