$primary_paletteKeyColor = 826ca7
$secondary_paletteKeyColor = 7d7389
$tertiary_paletteKeyColor = 9a6a75
$neutral_paletteKeyColor = 7a757c
$neutral_variant_paletteKeyColor = 7a757f
$background = 151218
$onBackground = e7e0e8
$surface = 151218
$surfaceDim = 151218
$surfaceBright = 3b383e
$surfaceContainerLowest = 0f0d12
$surfaceContainerLow = 1d1a20
$surfaceContainer = 211e24
$surfaceContainerHigh = 2c292f
$surfaceContainerHighest = 37343a
$onSurface = e7e0e8
$surfaceVariant = 49454e
$onSurfaceVariant = cbc4cf
$inverseSurface = e7e0e8
$inverseOnSurface = 322f35
$outline = 958e99
$outlineVariant = 49454e
$shadow = 000000
$scrim = 000000
$surfaceTint = d4bbfc
$primary = d4bbfc
$onPrimary = 3a255b
$primaryContainer = 513c73
$onPrimaryContainer = ecdcff
$inversePrimary = 69548d
$secondary = cec2db
$onSecondary = 342d40
$secondaryContainer = 50485c
$onSecondaryContainer = eadef7
$tertiary = f1b7c3
$onTertiary = 4a252f
$tertiaryContainer = b7838e
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ecdcff
$primaryFixedDim = d4bbfc
$onPrimaryFixed = 240e45
$onPrimaryFixedVariant = 513c73
$secondaryFixed = eadef7
$secondaryFixedDim = cec2db
$onSecondaryFixed = 1f182a
$onSecondaryFixedVariant = 4b4357
$tertiaryFixed = ffd9e0
$tertiaryFixedDim = f1b7c3
$onTertiaryFixed = 32101a
$onTertiaryFixedVariant = 643b45
$term0 = 353434
$term1 = ce5dff
$term2 = ffbac2
$term3 = ffdcf2
$term4 = a4a6d8
$term5 = c49ae2
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = dd85ff
$term10 = ffd2d5
$term11 = fff0f6
$term12 = babfdd
$term13 = d8b1ed
$term14 = bae0ff
$term15 = ffffff
$rosewater = faeef7
$flamingo = eedcf0
$pink = ecd4ff
$mauve = d1b2ff
$red = d4a0f3
$maroon = d6b2e6
$peach = ecbff0
$yellow = ffecf3
$green = c8e3ff
$teal = dbddff
$sky = d9d7ff
$sapphire = c5c1ff
$blue = c2b2ff
$lavender = d5c4ff
$klink = 877ccf
$klinkSelection = 887ccf
$kvisited = 976bd1
$kvisitedSelection = 986bd0
$knegative = bc5dec
$knegativeSelection = bd5deb
$kneutral = e882ff
$kneutralSelection = ea81ff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e7e0e8
$subtext1 = cbc4cf
$subtext0 = 958e99
$overlay2 = 827b86
$overlay1 = 6e6872
$overlay0 = 5c5760
$surface2 = 4b464f
$surface1 = 3a363d
$surface0 = 27242a
$base = 151218
$mantle = 151218
$crust = 141117
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
